order/__init__.py
"""
author:何凯
date:
"""

order/views.py
"""
author:何凯
date:
"""
from flask import Blueprint, render_template, request, jsonify, session
from time import strftime,strptime
from datetime import datetime

from sqlalchemy import or_, and_

from models import House, Order
from utils.functions import is_auth

order = Blueprint('order',__name__)


@order.route('/booking/',methods=['GET'])
def booking_get():
    return render_template('booking.html')


@order.route('/booking/',methods=['POST'])
def booking_post():
    pass


@order.route('/get_booking_house/',methods = ['POST'])
def get_booking_house():
    id = request.form.get('id')
    house = House.query.get(id)
    # 判断是否是本人发布的房源
    user_id = session.get('user_id')
    house_user_id = house.user_id
    is_mine = False
    if user_id == house_user_id:
        is_mine = True
    info = [house.to_dict()]
    return jsonify({'code':200,'houses':info,'is_mine':is_mine})


@order.route('/make_order/',methods = ['POST'])
@is_auth
def make_order():
    data = request.form
    id = data.get('id')
    sd = data.get('start_date')
    ed = data.get('end_date')
    # 对订单时间进行验证
    # 得到正在使用的house
    orders = Order.query.filter(Order.status.in_(["WAIT_ACCEPT", "WAIT_PAYMENT", "PAID"]))
    # 根据时间来筛选house
    if (sd and ed):
        start_date = datetime.strptime(sd, "%Y-%m-%d")
        end_date = datetime.strptime(ed, "%Y-%m-%d")
        house_inuse = orders.filter(
            or_(and_(Order.end_date <= end_date, Order.end_date >= start_date), and_(Order.begin_date <= end_date, Order.begin_date >= start_date)))
        hosue_inuse_id = [house.house_id for house in house_inuse]
    else:
        # 如果开始时间，结束时间没填全，返回错误
        return jsonify({'code':1001,'msg':'参数不全'})
    if id in hosue_inuse_id:
        return jsonify({'code': 1001, 'msg': '房子在使用'})

    # 创建订单
    order = Order()
    order.user_id = session.get('user_id')
    order.house_id = id
    order.begin_date = start_date
    order.end_date = end_date
    start_date = strptime(sd,'%Y-%m-%d')
    end_date = strptime(ed,'%Y-%m-%d')
    start_date = datetime(start_date[0],start_date[1],start_date[2])
    end_date = datetime(end_date[0],end_date[1],end_date[2])
    order.days = (end_date-start_date).days+1
    order.house_price = House.query.get(id).price
    order.amount = order.days*order.house_price
    order.add_update()
    return jsonify({'code':200,'amount':order.amount})

user/views.py
"""
author:何凯
date:
"""
import os
import random
import re

from flask import Blueprint, render_template, jsonify, session, url_for, request, redirect

from models import User, House, Order, db
from utils.functions import is_login, check_idcard, is_auth
from utils.settings import IMAGES_DIR
from utils.status_code import *

user = Blueprint('user', __name__)


@user.route('/register/', methods = ['GET'])
def register_get():
    return render_template('register.html')


@user.route('/register/', methods = ['POST'])
def register_post():
    phone = request.form.get('phone')
    imagecode = request.form.get('imagecode')
    password = request.form.get('password')
    password2 = request.form.get('password2')
    img_code = session.get('img_code')
    if not all([phone, imagecode, password, password2]):
        # 判断所有字段中是否有空
        return jsonify({'empty': FIELD_IS_EMPTY})
    error = {}
    # 手机号验证
    ret = re.match(r"^1[35678]\d{9}$", phone)
    if not ret:
        error['phone'] = USER_PHONE_ERROR
    # 图片验证码验证
    if imagecode != img_code:
        error['imagecode'] = IMG_CODE_ERROR
    # 密码位数验证
    if len(password) < 6:
        error['password_less'] = PASSWORD_LESS
    # 两次密码是否相同
    if password != password2:
        error['password_different'] = TWO_PASSWORD_DIFFERENT
    # 如果有错，返回错误信息
    if error:
        return jsonify(error)
    # 没错返回登陆页面，并存储用户数据
    new_user = User()
    new_user.phone = phone
    new_user.password = password
    new_user.add_update()
    return jsonify({'code':200})


@user.route('/get_img_code/', methods = ['GET'])
def get_img_code():
    img_codes = '1234567890qwertyuiopalwskdjfhgmzxcvbn'
    img_code = ''
    for _ in range(4):
        img_code += random.choice(img_codes)
    session['img_code'] = img_code
    return jsonify({'code': 200, 'data': img_code})


@user.route('/login/', methods = ['GET'])
def login_get():
    return render_template('login.html')


@user.route('/login/', methods = ['POST'])
def login_post():
    phone = request.form.get('mobile')
    password = request.form.get('password')
    user = User.query.filter(User.phone == phone).first()
    if user :
        if user.check_pwd(password):
            session['user_id'] = user.id
            return jsonify({'code':200})
    return jsonify({'error':'请输入正确的电话号码和密码'})


@user.route('/my/',methods = ['GET'])
@is_login
def my():
    return render_template('my.html')


@user.route('/get_user/',methods=['POST'])
def get_user():
    user_id = session.get('user_id')
    if not user_id:
        return jsonify({'code':1001})
    user = User.query.get(user_id)
    avatar =user.avatar
    id_name = user.id_name
    id_card = user.id_card
    if not user.name:
        user.name = user.phone
    return jsonify({'code':200,'id_name':id_name,'id_card':id_card,'phone':user.phone,'name':user.name,'avatar':avatar})


@user.route('/auth/',methods = ['GET'])
@is_login
def auth_get():
    return render_template('auth.html')


@user.route('/auth/',methods = ['POST'])
@is_login
def auth_post():
    # 实名认证
    real_name = request.form.get('real_name')
    id_card = request.form.get('id_card')
    # 验证name,id_card
    if not all([real_name,id_card]):
        return jsonify({'error':FIELD_IS_EMPTY})
    # 验证唯一性

    regex_name = r'[\u4E00-\u9FA5]{2,}'
    if not re.match(regex_name,real_name):
        return jsonify({'error':NOT_CORRENT_NAME})
    error = check_idcard(id_card)
    if error != '验证通过!':
        return jsonify({'error':error})
    # 验证成功
    user_id = session['user_id']
    user = User.query.get(user_id)
    user.id_name = real_name
    user.id_card = id_card
    user.add_update()

    return jsonify({'code':200})


@user.route('/profile/',methods = ['GET'])
@is_login
def profile_get():
    return render_template('profile.html')
# avatar

@user.route('/upload_img/',methods = ['POST'])
@is_login
def upload_img():
    # 获取图片并保存
    icon = request.files.get('avatar')
    path = os.path.join(IMAGES_DIR,icon.filename)
    icon.save(path)
    # 保存到数据库
    user_id = session['user_id']
    user = User.query.get(user_id)
    user.avatar = icon.filename
    user.add_update()
    return jsonify({'code':200,'avatar':icon.filename})


@user.route('/upload_name/',methods = ['POST'])
@is_login
def upload_name():
    name= request.form.get('name')
    user_id = session['user_id']
    user = User.query.get(user_id)
    user.name = name
    user.add_update()
    return jsonify({'code':200,'name':name})


@user.route('/logout/',methods=['GET'])
@is_login
def logout():
    session.clear()
    return jsonify({'code':200})


@user.route('/myhouse/',methods = ['GET'])
@is_login
def my_house():
    return render_template('myhouse.html')

@user.route('/get_myhouse/',methods=['GET'])
@is_login
def get_myhouse():
    user_id = session.get('user_id')
    houses = House.query.filter(House.user_id == user_id).all()
    data = []
    if houses :
        for house in houses:
            data.append(house.to_dict())
        return jsonify({'code':200,'houses':data})
    return jsonify({'code':IS_NULL,})


@user.route('/my_orders/',methods = ['GET'])
@is_auth
def my_orders():
    return render_template('orders.html')


@user.route('/get_myorders/',methods = ['GET'])
@is_auth
def get_myorders():
    user_id = session.get('user_id')
    orders = Order.query.filter(Order.user_id == user_id).order_by('-create_time').all()
    data = []
    for order in orders:
        order = order.to_dict()
        comment = order['comment']
        if str(comment).startswith('REJECTED'):
            order['comment']=''
            order['rejected']=comment[8:]
        data.append(order)

    return jsonify({'code':200,'orders':data})



@user.route('/my_lorders/',methods=['GET'])
@is_auth
def my_lorders():
    return render_template('lorders.html')


@user.route('/get_mylorders/',methods=['GET'])
def get_mylorders():
    user_id = session.get('user_id')
    houses = House.query.filter(House.user_id == user_id).all()
    orders = [house.orders for house in houses]
    my_lorders = []
    for order in orders:
        my_lorders += order
    # 注意列表中的为对象，还要将它的数据进行处理
    if my_lorders:
        my_lorders = [order.to_dict() for order in my_lorders]
        my_lorders = sorted(my_lorders,key=lambda my_order:my_order['order_id'],reverse=True)

    return jsonify({'code': 200, 'orders': my_lorders})

templates/auth.html
{% extends 'base_main.html' %}
{% block title %}
爱家-实名认证
{% endblock %}
{% block css %}
{{super()}}
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/profile.css" rel="stylesheet">
{%  endblock %}
{% block content %}
       <div class="top-bar">
            <div class="nav-bar">
                <h3 class="page-title">实名认证</h3>
                <a class="nav-btn fl" href="/my.html"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
        </div>
        <div class="menus-con">
            <ul class="menus-list">
                <li>
                    <div class="menu-title">
                        <h3>认证信息</h3>
                    </div>
                    <div class="menu-content">
                        <form id="form-auth" >
                            <div class="form-group">
                                <label for="real-name">真实姓名</label>
                                <input type="text" class="form-control" name="real_name" id="real-name" >
                            </div>
                            <div class="form-group">
                                <label for="id-card">身份证号码</label>
                                <input type="text" class="form-control" name="id_card" id="id-card">
                            </div> 
                            <div class="error-msg"><i class="fa fa-exclamation-circle"></i>信息填写不完整，请补全信息</div>
                            <input type="submit" class="btn btn-success" value="保存">
                        </form>
                    </div>
                </li>
            </ul>
        </div>
        <div class="popup_con">
            <div class="popup">
                <p>保存成功！</p>
            </div>
            
            <div class="mask"></div>
        </div>
{% endblock %}
{% block js %}
{{super()}}
    <script src="/static/js/jquery.form.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/auth.js"></script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}
</head>
<body>
{% block body %}
{% endblock %}

{% block js %}
{% endblock %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% block js %}
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/plugins/bootstrap/js/bootstrap.min.js"></script>
    <script>
        $('.nav-btn').on('click',function(e){
            e.preventDefault()
            window.history.back();
        })
    </script>
{% endblock %}
{% block css %}
    <link href="/static/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/css/reset.css" rel="stylesheet">
    <link href="/static/css/ihome/main.css" rel="stylesheet">
{% endblock %}

{% block body %}

<div class="container">
{% block content %}
{% endblock %}
{% block footer %}
 <div class="footer">
            <p><span><i class="fa fa-copyright"></i></span>爱家租房&nbsp;&nbsp;享受家的温馨</p>
        </div>
{% endblock %}
</div>

{% endblock %}

templates/booking.html
{% extends 'base_main.html' %}
{% block title %}
爱家-预订
{% endblock %}
{% block css %}
    {{super()}}
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/booking.css" rel="stylesheet">
{% endblock %}
{% block content %}

    <div class="top-bar">
        <div class="nav-bar">
            <h3 class="page-title">预 订</h3>
            <a class="nav-btn fl" ><span><i class="fa fa-angle-left fa-2x"></i></span></a>
        </div>
    </div>
    <div class="house-info">
        <img src="" id="house_img">
        <div class="house-text">
            <h3 id="house_title">房屋标题</h3>
            <p>￥<span id="house_price"></span>/晚</p>
        </div>
    </div>
    <div class="select-date">
        <div class="select-date-header">入住时间</div>
        <div class="input-daterange input-group">
            <input type="text" class="input-sm form-control" id="start-date" />
            <span class="input-group-addon">至</span>
            <input type="text" class="input-sm form-control" id="end-date" />
        </div>
    </div>
    <div class="submit-order">
        <input type="text" id="order_amount">
        <span class="order-amount">订单总额：<span ></span></span>
        <span class="submit-btn">提交订单</span>
    </div>
    <div class="popup_con">
        <div class="popup">
            <p>日期有误，请重新选择！</p>
        </div>
        <div class="mask"></div>
    </div>
{% endblock %}
{% block footer %}
{% endblock %}
{% block js %}
    {{super()}}
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/booking.js"></script>
{% endblock %}

templates/detail.html
{% extends 'base_main.html' %}
{% block title %}
爱家-房间信息
{% endblock %}
{% block css %}
{{ super() }}
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/detail.css" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="top-bar">
        <div class="nav-bar">
                <h3 class="page-title">房间信息</h3>
                <a class="nav-btn fl" ><span><i class="fa fa-angle-left fa-2x"></i></span></a>
            </div>
    </div>
    <div class="swiper-container">
        <ul class="swiper-wrapper">
        </ul>
        <div class="swiper-pagination"></div>
        <div class="house-price">￥<span>300</span>/晚</div>
    </div>
    <div class="detail-con">
        <div class="detail-header layout-style">
            <h2 class="house-title"></h2>
            <div class="landlord-pic"><img src="/static/images/landlord01.jpg"></div>
            <h2 class="landlord-name">房东： <span></span></h2>
        </div>
        <div class="house-info layout-style">
           <h3>房屋地址</h3>
           <ul class="house-info-list text-center">
                <li id="house_address"></li>
           </ul>
        </div>
        <ul class="house-type layout-style">
            <li>
                <span class="icon-house"></span>
                <div class="icon-text" id="house_info">
                </div>
            </li>
            <li>
                <span class="icon-user"></span>
                <div class="icon-text" id="house_capacity">

                </div>
            </li>
            <li>
                <span class="icon-bed"></span>
                <div class="icon-text" id="house_beds">
                    <h3>卧床配置</h3>
                </div>
            </li>
        </ul>
        <div class="house-info layout-style">
            <h3>房间详情</h3>
            <ul class="house-info-list">
                <li>收取押金<span id="house_deposit"></span></li>
                <li>最少入住天数<span id="house_min_days"></span></li>
                <li>最多入住天数<span id="house_max_days"></span></li>
            </ul>
        </div>
        <div class="house-facility layout-style">
            <h3>配套设施</h3>
            <ul class="house-facility-list clearfix">

            </ul>
        </div>
        <div class="house-info layout-style">
            <h3>评价信息</h3>
            <ul class="house-comment-list">
                <li>
                    <p>小鲜肉<span class="fr">2016-11-11 20:00:00</span></p>
                    <p>哎呦不错喔！！</p>
                </li>
            </ul>
        </div>
    </div>
    <a class="book-house" href="">即刻预定</a>
{% endblock %}
{% block js %}
{{ super() }}
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/detail.js"></script>
{% endblock %}

templates/index.html
{% extends 'base_main.html' %}
{% block title %}
爱家
{% endblock %}
{% block css %}
{{ super() }}
    <link href="/static/plugins/swiper/css/swiper.min.css" rel="stylesheet">
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/index.css" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="top-bar">
        <img class="logo fl" src="/static/images/logo@128x59.png">
        <div class="register-login fr">
            <a class="btn top-btn btn-theme" href="/register.html">注册</a>
            <a class="btn top-btn btn-theme" href="/login.html">登录</a>
        </div>
        <div class="user-info fr"><span><i class="fa fa-user fa-lg"></i></span> <a class="user-name" href="/user/my/"></a></div>
    </div>
    <div class="swiper-container">
        <div class="swiper-wrapper">


        </div>
        <div class="swiper-pagination"></div>
    </div>
    <div class="search-bar">
        <button class="filter-btn" type="button" data-toggle="modal" data-target="#area-modal"><span class="fl" id="area-btn">选择城区</span><span class="fr"><i class="fa fa-map-marker fa-lg fa-fw"></i></span></button>
        <button class="filter-btn" type="button" data-toggle="modal" data-target="#start-date-modal"><span class="fl" id="start-date-btn">入住日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
        <button class="filter-btn end-date" type="button" data-toggle="modal" data-target="#end-date-modal"><span class="fl" id="end-date-btn">离开日期</span><span class="fr"><i class="fa fa-calendar fa-lg fa-fw"></i></span></button>
        <a class="btn search-btn btn-theme" href="#" onclick="goToSearchPage(this);" area-id="" start-date="" end-date="">搜索</a>
        <div class="modal fade" id="area-modal" tabindex="-1" role="dialog" aria-labelledby="area-label">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="area-label">选择城区</h4>
                    </div>
                    <div class="modal-body">
                        <div class="area-list">
                            <!--<a href="#" area-id="1">东城区</a>-->

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="start-date-modal" tabindex="-1" role="dialog" aria-labelledby="start-date-label">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="start-date-label">入住日期</h4>
                    </div>
                    <div class="modal-body">
                        <div class="date-select" id="start-date"></div>
                        <input type="hidden" id="start-date-input">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-theme" onclick="setStartDate();">确定</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="end-date-modal" tabindex="-1" role="dialog" aria-labelledby="end-date-label">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="end-date-label">离开日期</h4>
                    </div>
                    <div class="modal-body">
                        <div class="date-select" id="end-date"></div>
                        <input type="hidden" id="end-date-input">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-theme" onclick="setEndDate();">确定</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ super() }}
    <script src="/static/plugins/swiper/js/swiper.jquery.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/template.js"></script>
    <script src="/static/js/ihome/index.js"></script>
{% endblock %}

templates/login.html
{% extends 'base_main.html' %}
{% block title %}
爱家-登陆
{% endblock %}
{% block css %}
{{super()}}
    <link href="/static/css/ihome/login.css" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="container">
        <div class="logo-bar"><a href="/"><img src="/static/images/logo@128x59.png"></a></div>
        <form class="form-login">
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-user fa-lg fa-fw"></i></div>
                    <input type="number" class="form-control" name="mobile" id="mobile" placeholder="手机号" required>
                </div>
            </div>
            <div class="error-msg" id="mobile-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-lock fa-lg fa-fw"></i></div>
                    <input type="password" class="form-control" name="password" id="password" placeholder="密码" required>
                </div>
            </div>
            <div class="error-msg" id="password-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <input type="submit" class="btn btn-lg btn-theme btn-block" value="登录" >
            <p class="register-a">没有账号，<a href="{{ url_for('user.register_get') }}">立即注册</a></p>
        </form>
    </div>
{% endblock %}
{% block js %}
{{super()}}
    <script src="/static/js/ihome/login.js"></script>
{% endblock %}

templates/my.html
{% extends 'base_main.html' %}
{% block title %}
爱家-我的爱家
{% endblock %}
{% block css %}
{{ super() }}
    <link href="/static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="/static/css/ihome/my.css" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="top-bar">
        <div class="nav-bar">
            <h3 class="page-title">我的爱家</h3>
            <a class="nav-btn fl"><span><i class="fa fa-angle-left fa-2x"></i></span></a>
        </div>
    </div>
    <div class="menus-con">
        <ul class="menus-list">
            <li>
                <div class="menu-title">
                    <h3>个人信息</h3>
                    <a class="fr" href="{{url_for('user.profile_get')}}">修改</a>
                </div>
                <div class="menu-content">
                    <img id="user-avatar" src="">
                    <div class="menu-text">
                        <h3>用户名：<span id="user-name"></span></h3>
                        <h5>手机号：<span id="user-mobile"></span></h5>
                    </div>
                </div>
            </li>
            <li>
                <div class="menu-title menu-radius">
                    <a href="/user/my_orders/"><h3>我的订单</h3></a>
                </div>
            </li>
            <li>
                <div class="menu-title menu-radius">
                    <a href="{{url_for('user.auth_get')}}"><h3>实名认证</h3></a>
                </div>
            </li>
            <li>
                <div class="menu-title menu-radius">
                    <a href="/user/myhouse/"><h3>我的房源</h3></a>
                </div>
            </li>
            <li>
                <div class="menu-title menu-radius">
                    <a href="/user/my_lorders/"><h3>客户订单</h3></a>
                </div>
            </li>
            <li>
                <div class="menu-title menu-radius">
                    <a href="" onclick="logout();" >退出</a>
                </div>
            </li>
        </ul>
    </div>
{% endblock %}

{% block js %}
{{ super() }}
    <script src="/static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="/static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
    <script src="/static/js/ihome/my.js"></script>
{% endblock %}

templates/register.html
{% extends 'base_main.html' %}
{% block title %}
爱家-注册
{% endblock %}
{% block css %}
    {{super()}}
    <link href="/static/css/ihome/register.css" rel="stylesheet">
{% endblock %}
{% block body %}
    <div class="container">
        <div class="logo-bar"><a href="/"><img src="/static/images/logo@128x59.png"></a></div>
        <form class="form-register">
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-mobile fa-2x fa-fw"></i></div>
                    <input type="number" class="form-control" name="mobile" id="mobile" placeholder="手机号" required>
                </div>
            </div>
            <div class="error-msg" id="mobile-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-image fa-lg fa-fw"></i></div>
                    <input type="text" class="form-control" name="imagecode" id="imagecode" placeholder="图片验证码" required>
                    <div class="input-group-addon image-code" onclick="generateImageCode();"><img></div>
                </div>
            </div>
            <div class="error-msg" id="image-code-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-envelope-o fa-lg fa-fw"></i></div>
                    <input type="text" class="form-control" name="phonecode" id="phonecode" placeholder="短信验证码" required>
                    <div class="phonecode input-group-addon">
                        <a class="phonecode-a" href="javascript:;" onclick="sendSMSCode();">获取验证码</a>
                    </div>
                </div>
            </div>
            <div class="error-msg" id="phone-code-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-lock fa-lg fa-fw"></i></div>
                    <input type="password" class="form-control" name="password" id="password" placeholder="密码" required>
                </div>
            </div>
            <div class="error-msg" id="password-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <div class="form-group form-group-lg">
                <div class="input-group">
                    <div class="input-group-addon"><i class="fa fa-lock fa-lg fa-fw"></i></div>
                    <input type="password" class="form-control" name="password2" id="password2" placeholder="确认密码" required>
                </div>
            </div>
            <div class="error-msg" id="password2-err"><i class="fa fa-exclamation-circle"></i><span></span></div>
            <input type="submit" class="btn btn-lg btn-theme btn-block" id="register_now" value="立即注册">
            <p class="login-a">已有账号，<a href="{{ url_for('user.login_get') }}">立即登陆</a></p>
        </form>
    </div>
{% endblock %}
{% block js %}
{{super()}}
    <script src="/static/js/ihome/register.js"></script>
{% endblock %}